apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    service: greeting
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      service: greeting
  template:
    metadata:
      labels:
        service: greeting
        autotrace: enabled
    spec:
      containers: 
      - name: greeting
        image: greeting-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
#         env:
#         - name: SFX_ACCESS_TOKEN
#           valueFrom:
#             secretKeyRef:
#               name: signalfx-agent
#               key: access-token
#         - name: MY_POD_NAME
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.name
#         - name: MY_NODE_NAME
#           valueFrom:
#             fieldRef:
#               apiVersion: v1
#               fieldPath: spec.nodeName
#         - name: MY_NAMESPACE
#           valueFrom:
#             fieldRef:
#               apiVersion: v1
#               fieldPath: metadata.namespace
#         - name: SIGNALFX_AGENT_HOST
#           valueFrom:
#             fieldRef:
#               apiVersion: v1
#               fieldPath: status.hostIP
# #        - name: SIGNALFX_ENDPOINT_URL
# #          value: http://zipkin:9411/api/v2/spans
#         - name: SIGNALFX_SERVICE_NAME
#           value: greeting             